name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Adjust the timeout as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Install Criterion
        run: |
          curl -o criterion.tar.xz -L https://github.com/Snaipe/Criterion/releases/download/v2.4.1/criterion-2.4.1-linux-x86_64.tar.xz
          tar xvf criterion.tar.xz
          sudo cp -r criterion-2.4.1/include /usr/local/
          sudo cp -r criterion-2.4.1/lib /usr/local/
          sudo ldconfig

      - name: Build and run tests
        run: |
          make
          make test
